apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: <value>
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: <value>
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: <value>
      # Each version can be enabled/disabled by Served flag.
      served: <value>
      # One and only one version must be marked as the storage version.
      storage: <value>
      schema:
        openAPIV3Schema:
          type: object
          properties:
            <key>:
              type: <value>
              description: <value>
  # either Namespaced or Cluster
  scope: <value>
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: <value>
    # singular name to be used as an alias on the CLI and for display
    singular: <value>
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: <value>
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - <value>
