apiVersion: apps/v1
kind: Deployment
metadata:
  name: <value>
  labels:
    app: <value>
spec:
  replicas: <value>
  selector:
    matchLabels:
      app: <value>
  template:
    metadata:
      labels:
        app: <value>
    spec:
      containers:
      - name: <value>
        image: <value>
        ports:
        - containerPort: <value>
      imagePullSecrets:
      - name: <value>
