apiVersion: v1
kind: Service
metadata:
  name: <value>
spec:
  type: NodePort
  selector:
    app: <value>
  ports:
    - name: <value>
      protocol: <value>
      port: <value>
      targetPort: <value>
      nodePort: <value>